apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-creds
  namespace: argocd
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend 
    kind: SecretStore

  target:
    name: repo-creds
    creationPolicy: Owner

    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        url: git@github.com:Ajaz3800/gitops-platform-repo.git
        sshPrivateKey: "{{ .sshPrivateKey }}"
        insecure: "false"
