apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend-secretstore
  namespace: securestore
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    vault:
      server: "https://192.168.56.13:8200"
      path: "secret"
      version: "v2"
      caProvider:
        type: Secret
        name: vault-ca-cert
        key: ca.crt
        namespace: securestore
      auth:
        kubernetes:
          mountPath: "kubernetes-secret-store"
          role: "securestore-role"
          serviceAccountRef:
            name: vault-secret-auth
            namespace: securestore
          secretRef:
            name: vault-secret-auth-token
            key: token