apiVersion: v1
kind: Secret
metadata:
  name: vault-secret-auth-token
  namespace: securestore
  annotations:
    kubernetes.io/service-account.name: vault-secret-auth
type: kubernetes.io/service-account-token