apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-extra-permissions
rules:
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eso-extra-permissions
subjects:
  - kind: ServiceAccount
    name: external-secrets-cert-controller
    namespace: external-secrets
roleRef:
  kind: ClusterRole
  name: eso-extra-permissions
  apiGroup: rbac.authorization.k8s.io