apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco-extra
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falco-extra
subjects:
  - kind: ServiceAccount
    name: falco
    namespace: falco
roleRef:
  kind: ClusterRole
  name: falco-extra
  apiGroup: rbac.authorization.k8s.io