apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  description: Platform components (observability)

  sourceRepos:
    - git@github.com:Ajaz3800/gitops-platform-repo.git
    - https://kubernetes-sigs.github.io/metrics-server/
    - https://prometheus-community.github.io/helm-charts

  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc

    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: apiregistration.k8s.io
      kind: APIService
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: ""
      kind: Namespace
