apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privilege-escalation
spec:
  validationFailureAction: Enforce
  background: true

  rules:
    - name: privilege-escalation
      match:
        any:
          - resources:
              kinds:
                - Pod

      validate:
        message: "Privilege escalation is not allowed."
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.containers[].securityContext.allowPrivilegeEscalation }}"
                operator: Equals
                value: true

              - key: "{{ request.object.spec.securityContext.allowPrivilegeEscalation }}"
                operator: Equals
                value: true
