apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-probes
spec:
  validationFailureAction: Audit

  rules:
    - name: probes
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Liveness and readiness probes are required."
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.containers[].livenessProbe }}"
                operator: Equals
                value: null

              - key: "{{ request.object.spec.containers[].readinessProbe }}"
                operator: Equals
                value: null
