apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resources
spec:
  validationFailureAction: Audit

  rules:
    - name: validate-resources
      match:
        any:
          - resources:
              kinds:
                - Pod
              
      validate:
        message: "CPU and memory requests/limits are required."
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.containers[].resources.requests.cpu }}"
                operator: Equals
                value: null

              - key: "{{ request.object.spec.containers[].resources.requests.memory }}"
                operator: Equals
                value: null

              - key: "{{ request.object.spec.containers[].resources.limits.cpu }}"
                operator: Equals
                value: null

              - key: "{{ request.object.spec.containers[].resources.limits.memory }}"
                operator: Equals
                value: null
