apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-non-root
spec:
  validationFailureAction: Enforce
  background: true

  rules:
    - name: validate-run-as-non-root
      match:
        any:
          - resources:
              kinds:
                - Pod

      validate:
        message: "Containers must run as non-root."
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.containers[].securityContext.runAsUser }}"
                operator: Equals
                value: 0

              - key: "{{ request.object.spec.securityContext.runAsNonRoot }}"
                operator: Equals
                value: false
