apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-security
  namespace: argocd

spec:
  description: Platform components (security)

  sourceRepos:
    - https://kyverno.github.io/kyverno
    - https://falcosecurity.github.io/charts

  destinations:
    - namespace: falco
      server: https://kubernetes.default.svc

    - namespace: kyverno
      server: https://kubernetes.default.svc