apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-security
  namespace: argocd

spec:
  description: Platform components (security)

  sourceRepos:
    - git@github.com:Ajaz3800/gitops-platform-repo.git
    - https://kyverno.github.io/kyverno
    - https://falcosecurity.github.io/charts

  destinations:
    - namespace: falco
      server: https://kubernetes.default.svc

    - namespace: kyverno
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition