apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend-secretstore
  namespace: securestore
spec:
  provider:
    vault:
      server: "https://192.168.56.13:8200"
      path: "secret"
      version: "v2"
      caProvider:
        type: Secret
        name: vault-ca-cert
        key: ca.crt
        namespace: securestore
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "securestore-role"
          serviceAccountRef:
            name: vault-secret-auth
            namespace: securestore