apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-rollouts/application.yaml
  - cert-manager/application.yaml
  - external-secrets/application.yaml
  - ingress-nginx/application.yaml
  - falco/application.yaml
  - kyverno/application.yaml
  - monitoring/application.yaml
  - metrivs-server/application.yaml