apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: k8s-security
  source:
    repoURL: https://kyverno.github.io/kyverno
    chart: kyverno
    targetRevision: 3.8.0
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
        - /metadata/managedFields
        - /metadata/resourceVersion
        - /metadata/generation
    - group: apps
      kind: Deployment
      name: kyverno-admission-controller
      namespace: kyverno
      jqPathExpressions:
        - .spec.template.spec.containers[].args
    - group: apps
      kind: Deployment
      name: kyverno-background-controller
      namespace: kyverno
      jqPathExpressions:
        - .spec.template.spec.containers[].args
    - group: apps
      kind: Deployment
      name: kyverno-reports-controller
      namespace: kyverno
      jqPathExpressions:
        - .spec.template.spec.containers[].args