apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Infrastructure layer (RBAC, Vault, base configs)
  sourceRepos:
    - git@github.com:Ajaz3800/gitops-platform-repo.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: external-secrets.io
      kind: ClusterSecretStore
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: Secret
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: ConfigMap
    - group: external-secrets.io
      kind: SecretStore
    - group: external-secrets.io
      kind: ExternalSecret
  clusterResourceBlacklist:
    - group: ""
      kind: Node
    - group: ""
      kind: PersistentVolume