apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: k8s-infra
  source:
    repoURL: git@github.com:Ajaz3800/gitops-platform-repo.git
    path: infra/manifests/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOption:
      - CreateNamespace=true